name: Deploy Cloud Custodian Policies

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    
    env:
      AWS_DEFAULT_REGION: us-east-1
      POLICY_FOLDERS: |
        policies/securitygroup
        policies/unused-resources

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Install Cloud Custodian
    - name: Install Cloud Custodian
      run: |
        python3 -m venv custodian
        source custodian/bin/activate
        pip install c7n c7n-org c7n-mailer

    # Run c7n-mailer
    - name: Run c7n-mailer
      run: |
        source custodian/bin/activate
        echo "Running c7n-mailer"
        c7n-mailer --config policies/unused-resources/mailer.yml -t policies/unused-resources/templates --update-lambda

    # Validate and Run multiple Cloud Custodian policies
    - name: Validate and Run Cloud Custodian policies
      run: |
        source custodian/bin/activate

        # Loop through each policy folder and run the policies
        for folder in $POLICY_FOLDERS; do
          echo "Validating and running policies in $folder"

          # Validate the policy
          custodian validate $folder/policy.yml

          # If validation passes, run the policy using c7n-org
          c7n-org run -c $folder/accounts.yml -s output/$folder/ -u $folder/policy.yml --cache-period=0
        done
        
