name: Deploy Cloud Custodian Policies

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Cloud Custodian
      run: |
        python3 -m venv custodian
        source custodian/bin/activate
        pip install c7n
        pip install c7n-org
        pip install c7n-mailer

    # Run securitygroup policies using
    - name: Run securitygroup policies
      run: |
        source custodian/bin/activate
        c7n-org run -c policies/securitygroup/accounts.yml -s securitygroup/ -u policies/securitygroup/policy.yml --cache-period=0
